---
- name: define root password
  # vars_prompt:
  #   - name: user_password
  #     prompt: enter password for user
  # pwdhash: "{{ user_password | password_hash }}"
  # register: password_hash
  ansible.builtin.user:
    name: root 
    update_password: always 
    password: "{{ pwd_hash }}"
    # password: "{{ password_hash }}"
