---
# handlers file for server-setup
- name: restart sshd
  service: name=sshd state=restarted

- name: validate sshd configuration
  command: sshd -t -f /etc/ssh/sshd_config
  changed_when: false

- name: reload sshd
  service: name=sshd state=reloaded

- name: update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
